<?php
$ratesHtml = $block->getRatesHtml();
?>
<div style="border: 3px solid black;border-radius: 5px;display: flex">
    <div id="scroll-container" style="overflow: hidden; margin-right: 1%">
        <p id="scroll-text">
            <?= $ratesHtml ?>
        </p>
    </div>
    <a href="<?= $block->getUrl('fxrate') ?>" style="position: relative">
        <?= $block->escapeHtml('>>') ?>
    </a>
</div>
