<?php
$news = $block->getNews();
?>
<div class="business-news">
    <?php foreach ($news->getData() as $new) : ?>
        <div class="item">
            <a href="<?= $block->escapeHtml($new['link']) ?>" class="news-item">
                <div class="news-image">
                    <img src="<?= $block->escapeHtml($new['image_url']) ?>">
                </div>
                <div class="news-content">
                    <p class="title"><?= $block->escapeHtml($new['title']) ?></p>
                    <p class="description"><?= !empty($new['description']) ? $block->escapeHtml($new['description']) : '' ?></p>
                    <span class="pubDate"><?= $block->escapeHtml($new['pubdate']) ?></span>
                </div>
            </a>
        </div>
    <?php endforeach; ?>
</div>
<?= $block->getPagerHtml() ?>

