<?php
$apiKey = $block->getApiKey();
$unit = $block->getDefaultUnit();
$cityId = $block->getDefaultCityId();
$scriptUrl = $block->getWidgetScript();
$cityList = $block->getCitySelectData();
?>
<div id="openweathermap-widget-15"></div>
<script>
    require(['jquery'], function ($) {
        $(document).ready(function () {
            window.myWidgetParam ? window.myWidgetParam : window.myWidgetParam = [];
            initWidget('<?= $cityId ?>', '<?= $apiKey ?>', '<?= $unit ?>');
        })

        function initWidget(cityId, apiKey, unit) {
            window.myWidgetParam.push({
                id: 15,
                cityid: cityId,
                appid: apiKey,
                units: unit,
                containerid: 'openweathermap-widget-15'
            });
            (function () {
                var script = document.createElement('script');
                script.async = true;
                script.charset = "utf-8";
                script.src = "<?= $scriptUrl ?>";
                var s = document.getElementsByTagName('script')[0];
                s.parentNode.insertBefore(script, s);
            })();
        }
    })
</script>
